repos:
  - repo: https://github.com/GrandGaleTechnologies/behemoth-fastapi
    rev: v7.1.0  
    hooks:
      - id: flake8
        config_file: .flake8

  - repo: https://github.com/GrandGaleTechnologies/behemoth-fastapi
    rev: v3.3.1
    hooks:
      - id: MAIN
        config_file: .pylintrc

  - repo: https://github.com/GrandGaleTechnologies/behemoth-fastapi
    rev: v0.7.2
    hooks:
      - id: build
        config_file: railway.toml
  
  # - repo: local
  #   hooks:
  #     - id: run-alembic
  #       name: Alembic
  #       language: scripts
  #       entry: ./start.sh
