repos:
  - repo: https://github.com/Akashii0/behemoth-fastapi/tree/pre-commit-hook/.flake8
    rev: v7.1.0  
    hooks:
      - id: flake8

  - repo: https://github.com/Akashii0/behemoth-fastapi/tree/pre-commit-hook/.pylintrc
    rev: v3.3.1
    hooks:
      - id: pylint

  - repo: https://github.com/Akashii0/behemoth-fastapi/blob/pre-commit-hook/railway.toml
    rev: v0.7.2
    hooks:
      - id: ruff